#배포될 서버가 리눅스라 설정해줌
version: 0.0
os: linux

#아래 경로에서 실행
files:
  - source: /
    destination: /home/ubuntu/app
#실행 주체가 누구인지
permissions:
  - object: /home/ubuntu/app
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  # 배포 시 실행될 파일, deploy.sh는 배포파일을 우분투 내에 실행시켜줌
  AfterInstall:
    # location은 프로젝트의 root경로를 기준
    - location: deploy.sh
      timeout: 60
      runas: root
